
# Samplesheets


input_fofn: "${projectDir}/resources/seqera_nf_tower_data/manifest-6samples.txt"

# Main output dir

outdir: "s3://nf-tower-bucket/scratch/gatk4-germline-snps-indels-nf/results"

# Reference files

scattered_calling_interval: "${projectDir}/resources/seqera_nf_tower_data/hg38_wgs_scattered_calling_intervals.txt"

fasta: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/references/Homo_sapiens_assembly38.fasta"

dbSNP_vcf: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/references/Homo_sapiens_assembly38.dbsnp138.vcf"
 
known_indels_mills: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/references/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
 
known_indels_dbSNP: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/references/Homo_sapiens_assembly38.known_indels.vcf.gz"

sequence_grouping: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/sequence_grouping.txt"

sequence_grouping_unmapped: "s3://nf-tower-data/gatk4-germline-snps-indels-nf/sequence_grouping_with_unmapped.txt"


