# Local resources
unmapped_bams_list:
  "$baseDir/test_data/unmapped_bams.tsv"
sequence_grouping:
  "$baseDir/test_data/sequence_grouping.txt"
sequence_grouping_unmapped:
  "$baseDir/sequence_grouping_with_unmapped.txt"
scattered_calling_interval:
  "$baseDir/hg38_wgs_scattered_calling_intervals.txt"
input_fofn:
  "$baseDir/manifest-6samples.txt"

# Cloud resources
outdir:
  "s3://nextflow-ci/test_data/results/"
fasta:
  "s3://nextflow-ci/gatk4-germline-snps-indels/Homo_sapiens_assembly38.fasta"
dbSNP_vcf:
  "s3://nextflow-ci/gatk4-germline-snps-indels/Homo_sapiens_assembly38.dbsnp138.vcf"
known_indels_mills:
  "s3://nextflow-ci/gatk4-germline-snps-indels/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
known_indels_dbSNP:
  "s3://nextflow-ci/gatk4-germline-snps-indels/Homo_sapiens_assembly38.known_indels.vcf.gz"


