# References
fasta:
  "s3://gatk4-germline-snps-indels-nf/hg38/Homo_sapiens_assembly38.fasta"
dbSNP_vcf:
  "s3://gatk4-germline-snps-indels-nf/hg38/Homo_sapiens_assembly38.dbsnp138.vcf"
known_indels_mills:
  "s3://gatk4-germline-snps-indels-nf/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
known_indels_dbSNP:
  "s3://gatk4-germline-snps-indels-nf/hg38/Homo_sapiens_assembly38.known_indels.vcf.gz"

# List of samples to be analyzed
input_fofn:
  "s3://nextflow-ci/gatk4-germline-snps-indels/manifest-3samples.txt"

# Main output dir
outdir:
  "s3://nextflow-ci/gatk4-germline-snps-indels/results"

# Auxilliary files
unmapped_bams_list:
  "s3://nextflow-ci/gatk4-germline-snps-indels/unmapped_bams.tsv"
sequence_grouping:
  "s3://nextflow-ci/gatk4-germline-snps-indels/sequence_grouping.txt"
sequence_grouping_unmapped:
  "s3://nextflow-ci/gatk4-germline-snps-indels/sequence_grouping_with_unmapped.txt"
scattered_calling_interval:
  "s3://nextflow-ci/gatk4-germline-snps-indels/hg38_wgs_scattered_calling_intervals.txt"

